apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: laravel-app
          image: 890742596314.dkr.ecr.us-east-2.amazonaws.com/my-ecr-repo:latest
          ports:
            - containerPort: 9000